### ISSUE TITLE
Problem building documentation with overloaded functions

### ISSUE THREAD

**Issue by AkibAzmain** [svenevs/exhale#98] opened 2020-12-14 14:39 UTC
When I use exhale to generate documentation for my library with overloaded function, it shows warnings like this:

```
/home/akib/Projects/docview/docs/api/function_namespacedocview_1a23dabfacba6b32d41bd966ee72449980.rst:13: WARNING: doxygenfunction: Unable to resolve multiple matches for function "docview::unload_extension" with arguments (std::string) in doxygen xml output for project "libdocview" from directory: xml.
Potential matches:
    - void unload_extension(extension::extension &extension_object)
    - void unload_extension(std::string uuid)
/home/akib/Projects/docview/docs/api/function_namespacedocview_1ab268c8d6637aa0009f5ef5822efc10fe.rst:13: WARNING: doxygenfunction: Unable to resolve multiple matches for function "docview::unload_extension" with arguments (extension::extension&) in doxygen xml output for project "libdocview" from directory: xml.
Potential matches:
    - void unload_extension(extension::extension &extension_object)
    - void unload_extension(std::string uuid)
```

To diagnose the problem, I disabled Exhale and opened one of the files with problems. It had this line:

```rst
.. doxygenfunction:: docview::unload_extension(extension::extension&)
```

I changed the line to the following but the warning still showed:

```rst
.. doxygenfunction:: docview::unload_extension(extension::extension& extension_object)
```

Then I changed to this and the warning disappeared:

```rst
.. doxygenfunction:: docview::unload_extension(extension::extension &extension_object)
```

It looks like Breathe is very sensitive to whitespace and parameter names.

Is there any workaround?

Sphinx version: 3.3.1
Breathe version: 4.24.1
Exhale version: 0.2.3

**Note**: Although this issue is similar to #32, it's not the same or duplicate of that issue.

**Comment by svenevs** [comment] 2020-12-14 15:34
Oh my, the function overloads are back at it :scream:  It looks like maybe the rules in breathe have changed, thank you for producing a thorough bug report!

1. If you have time, could you try earlier versions of breathe to see if it stopped working at a certain point?  If earlier versions work then you could potentially pin your breathe version if you just need it to work :tm: (please report back if you find the latest functioning version).
2. Helpful reference, #45 is the changes that are relevant for function overloads which used to allow removing the variable name (which is why I excluded it from the parameter list).  It seems like maybe that's required now.  This is the code that generates `docview::unload_extension(extension::extension&)` currently:

    https://github.com/svenevs/exhale/blob/58c6c771fe021d7487644a30c2575b3fcf1ae94b/exhale/graph.py#L245-L250

    This is the code that parses / populates `self.parameters`:

    https://github.com/svenevs/exhale/blob/58c6c771fe021d7487644a30c2575b3fcf1ae94b/exhale/graph.py#L1999-L2003

    Note that the `santize_all` may now be a problem if you coerce `self.parameters` to include the parameter name in addition to the parameter type.
3. You can also in your `conf.py` introduce a funny hack to bypass this, untested but should be close enough to get you there, see [sphinx api docs on hooking into core events](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events) for more info:

    ```py
    def source_read(app, docname, source):
        # NOTE: not sure about docname, maybe just `print(docname)` to start out
        if docname == "api/function_namespacedocview_1a23dabfacba6b32d41bd966ee72449980.rst":
            source[0] = source[0].replace(
                ".. doxygenfunction:: docview::unload_extension(extension::extension&)",
                ".. doxygenfunction:: docview::unload_extension(extension::extension &extension_object)")
        elif docname == "api/function_namespacedocview_1ab268c8d6637aa0009f5ef5822efc10fe.rst":
            source[0] = source[0].replace(
                ".. doxygenfunction:: docview::unload_extension(std::string)",
                ".. doxygenfunction:: docview::unload_extension(std::string uuid)")

    def setup(app):  # called automatically for you by sphinx
        app.connect("source-read", source_read)
    ```

    But I may have mixed up the filenames, not sure, but the point is that you can ask sphinx to call your custom handler and then transform whatever documents you need to apply bandaids as needed.  Not pretty, but works :upside_down_face:

Wanted to send you a response, but the function overloads were really hacky and frustrating.  Long term, I want to PR to breathe to ask them if we can enable every directive to have a bypass for refid lookup.  So that we can e.g., `.. doxygenfunction:: __refid__::{function_refid}` or `.. doxygenclass:: __refid__::{class_refid}`.  That way we don't need to know the rules, which would fix the longstanding template function overload problem.  But that may be challenging to implement.

I'm not in a good place and don't know if or when that is going to change :disappointed:  So for now pretty much all open source is on hold for me.

**Comment by svenevs** [comment] 2020-12-14 15:51
Seems related: https://github.com/michaeljones/breathe/pull/606

I will try and test that PR quickly tonight after work, seems like a recent regression and I think my test cases may be helpful for them on this but have not run tests in ages...

**Comment by mattip** [comment] 2020-12-14 16:36
Note I have added tests to michaeljones/breathe#606 and fixed a minor issue with initialization values in a PR to that PR jakobandersen/breathe#1

**Comment by AkibAzmain** [comment] 2020-12-14 17:20
@svenevs I have fixed the problem. This fix works in my case. I have also submitted a pull request, #99.

**Comment by AkibAzmain** [comment] 2020-12-14 17:39
Oops, this repository still has this issue, reopening issue.

**Comment by AkibAzmain** [comment] 2020-12-15 10:26
@svenevs I'm confused about this bug. Is this is from upstream or a bug of both?

Also, using Breathe from pull request michaeljones/breathe#606 makes it work (with Exhale from `pip`).

**Comment by AkibAzmain** [comment] 2020-12-17 07:37
michaeljones/breathe#606 is merged, closing issue.

**Comment by aprotyas** [comment] 2021-07-22 05:09
I'm getting something similar still. In my case, the complaint is between `is_directory(const path&)` and `is_directory(const path& p)`. :disappointed:

**Comment by svenevs** [comment] 2021-07-22 16:42
Ok the rules probably changed again, using an earlier version of breathe may fix but I will have to look more closely. This fix is not without peril

**Comment by aprotyas** [comment] 2021-07-22 16:43
> Ok the rules probably changed again, using an earlier version of breathe may fix but I will have to look more closely. This fix is not without peril

Do you know a version of breathe I can pin to and try?

**Comment by svenevs** [comment] 2021-07-22 16:47
No :( probably 4.29 or 4.28 looking at the release dates for breathe on PyPI and that the PR 606 linked above fixed it.

I can't test at this moment but if you find one that works please post back. Sorry that's not very helpful :/

**Comment by aprotyas** [comment] 2021-07-29 05:23
I've tried with a couple of versions of `breathe` around v4.28, unfortunately nothing seemed to work for me.

**Comment by mattip** [comment] 2021-07-29 05:57
@aprotyas Can you post a complete example, preferably minimal,  that fails for you?

**Comment by aprotyas** [comment] 2021-07-29 07:05
@mattip I've attached as small an example as I could. To reproduce, run:

```bash
> doxygen Doxyfile
> sphinx-build . out
```

You should get an error that reads:

```
/tmp/exhale98/sample_proj/api/function_namespacefoo_1_1bar_1a4ba5a34f396d13152562b45891e82a13.rst:13: WARNING: doxygenfunction: Unable to resolve function "foo::bar::bad_function" with arguments (const int&) in doxygen xml output for project "svenevs_exhale_issue_98" from directory: doc_output/xml.
Potential matches:
 - bool bad_function(const int &p) noexcept
```

In hindsight, given the example I could reproduce with, this is not an "overloaded functions" problem precisely, but it is of a similar nature.

[svenevs_exhale_issue_98.tar.gz](https://github.com/svenevs/exhale/files/6898561/svenevs_exhale_issue_98.tar.gz)

**Comment by svenevs** [comment] 2022-01-01 00:03
closing with reference to #106, right now many overloads work, the ones that still fail are non-specialized template functions and sometimes global (not in a namespace) functions.  this bug does resurface differently over time, just trying to consolidate the function overloads discussion

**Closed by svenevs** 2022-01-01 00:03 UTC
Labels: bug
